site.host=
default.status=published
default.type=post
render.index=true
render.archive=false
render.feed=false
render.sitemap=false
render.tags=false
index.file=index.html
template.index.file=index.ftl
template.post.file=post.ftl
template.page.file=post.ftl
template.error404.file=404.ftl
error404.file=404.html
date.format=yyyy-MM-dd'T'HH:mm:ssX
db.store=plocal
db.path=cache
