BLOG_AUTHOR = "SSGBerk"
BLOG_TITLE = "Nikola Benchmark Site"
SITE_URL = "https://example.com/"
BLOG_EMAIL = "bench@example.com"
BLOG_DESCRIPTION = "Nikola benchmark site"
DEFAULT_LANG = "en"
TRANSLATIONS = {DEFAULT_LANG: ""}
NAVIGATION_LINKS = {}
THEME = "base"
POSTS = (("posts/*.md", "posts", "post.tmpl"),)
PAGES = ()
TIMEZONE = "UTC"
COMPILERS = {"markdown": (".md",)}
METADATA_FORMAT = "Nikola"
OUTPUT_FOLDER = "output"
CACHE_FOLDER = "cache"
PRETTY_URLS = True
COPY_SOURCES = False
SHOW_SOURCELINK = False
COMMENT_SYSTEM = ""
GENERATE_RSS = False
GENERATE_ATOM = False
SITEMAP_INCLUDE_FILELESS_DIRS = False
DISABLED_PLUGINS = ["sitemap", "robots"]
CREATE_ARCHIVE_NAVIGATION = False
CREATE_MONTHLY_ARCHIVE = False
CREATE_SINGLE_ARCHIVE = False
INDEX_PATH = ""
FRONT_INDEX_HEADER = ""
