runtime:
  cache_dir: ./.cache/antora
  fetch: false
  log:
    level: warn
site:
  title: SSGBerk Reference
content:
  sources:
    - url: .
      branches: HEAD
      worktrees: .
ui:
  bundle:
    url: ./ui-bundle.zip
output:
  dir: ./build/site
antora:
  extensions:
    - ./ssgberk-md-adapter.js
