baseurl = "http://staystatic.github.io/sites/hugo/"
languageCode = "en-us"
languageLang = "en"
defaultContentLanguage = "en"
title = "Hugo Stay Static Site Sample"
config = "config.toml"
disableKinds = ["page", "home", "section", "taxonomy", "taxonomyTerm"]
